### ISSUE TITLE
trust_list: Add OID info/filtering

### ISSUE THREAD

**Issue by wbond** [wbond/oscrypto#15]
Package Control will be switching to use `oscrypto.trust_list` for TLS trust roots to solve:

 - https://github.com/wbond/package_control/issues/1002
 - https://github.com/wbond/package_control/issues/1079

In order to do this, we need to tweak `trust_list.get_list()`. Ideally we need:

 1. A way to filter `get_list()` by one or more [key usage strings](https://github.com/wbond/asn1crypto/blob/master/asn1crypto/x509.py#L395-L406)/[extended key usage OIDs](https://github.com/wbond/asn1crypto/blob/master/asn1crypto/x509.py#L1531-L1595) 
 2. A new method such as `get_list()` that will return the list os trust roots along with a `set()` of their key usage names and extended key usage OIDs

**Comment by wbond** [comment]
There are three implementations of the `trust_list` module, one for each OS:

 - https://github.com/wbond/oscrypto/blob/master/oscrypto/_osx/trust_list.py
 - https://github.com/wbond/oscrypto/blob/master/oscrypto/_win/trust_list.py
 - https://github.com/wbond/oscrypto/blob/master/oscrypto/_linux_bsd/trust_list.py

**Comment by wbond** [comment]
Some OIDs need to be added for OS X: https://github.com/wbond/asn1crypto/issues/17

**Comment by wbond** [comment]
Additionally, we are going to need to add a "translation" layer for key purposes that will cover the "standard", OS X and Windows variations of OIDs. For instance, Windows uses `1.3.6.1.5.5.7.3.1` (a standard OID for server auth) for SSL, whereas OS X uses `1.2.840.113635.100.1.3`.

**Comment by wbond** [comment]
As of 41cb25705aabe33003c89dcc307c81cb23ee650b, `oscrypto.trust_list` now includes trust information for each certificate in the store, and `trust_list.get_path()` encodes the trust info into a format that OpenSSL understands.

**Comment by franklinyu** [comment]
Correct me if I am wrong: this issue is already fixed, and it will solve wbond/package_control#1079 and wbond/package_control#1002 in the next release, correct? So currently we just need to wait patiently for it?

**Comment by wbond** [comment]
@franklinyu This work will be used to replace the [existing code in Package Control for grabbing OS trust roots](https://github.com/wbond/package_control/blob/master/package_control/ca_certs.py).

**Comment by uchuugaka** [comment]
Any chance this would get resolved soon? This is one of the things that drives me nuts with Sublime.

**Comment by wbond** [comment]
@uchuugaka Work on this issue will continue as time allows. The next step is to add asn1crypto and oscrypto to Package Control as relative imports, possibly with unused submodules removed.

**Comment by ipv6freely** [comment]
Even if not fixed, is there at least a workaround to mute the message?

**Comment by FichteFoll** [comment]
@ipv6freely https://github.com/wbond/package_control/pull/1081

**Comment by ipv6freely** [comment]
@FichteFoll Thank you!
