### ISSUE TITLE
Implement none hash_algorithm for rsa_pkcs1v15_sign

### ISSUE THREAD

**Issue by asyd** [wbond/oscrypto#2]
To implement the https://github.com/spark/firmware protocol, I need to perform a signature with PKCS15 padding, but without applying a hash.

Thanks you!

**Comment by wbond** [comment]
This is now available by setting the `hash_algorithm` parameter of `asymmetric.rsa_pkcs1v15_sign()` or `asymmetric.rsa_pkcs1v15_verify()` to `"raw"`.
