### ISSUE TITLE
Can't use On Python3.7, Mac brew install python3

### ISSUE THREAD

**Issue by jacksonpan** [wbond/oscrypto#28]
today i upgrade to python3.7 with brew. but now i can't run my project and i find the problem was oscrypto.

![image](https://user-images.githubusercontent.com/696493/42194244-95e3000a-7ea5-11e8-95c2-d8b97f3e7f01.png)

i find the file(_libcrypto_ctypes.py) line: 258, 
        libcrypto.EVP_MD_CTX_new.argtypes = []
when run here then     raise FFIEngineError('Error initializing ctypes')
and the pic you can see in the libcrypto object, there is no object named EVP_MD_CTX_new.

can you fix it, soon?

when i use python3.6, it runs well

**Comment by wbond** [comment]
This bug has been fixed in master (83e2a06085b5b09ee5cd6c28a2ae1c52352c9e53, #22), but there hasn't been a release yet. Hopefully I can get one out somewhat soon. Until then, you can use pip to install from this git repo.

**Comment by drdaeman** [comment]
@wbond Sorry to bother - can you please consider creating a new release? There were a lot of useful bugfixes since 0.19.1...

**Comment by wbond** [comment]
Yes, I would like to do a release. I just had my fifth child, so free time is a bit sparse right now. Sorry!

**Comment by wbond** [comment]
Version 1.0.0 is out on PyPi - https://pypi.org/project/oscrypto/
