### ISSUE TITLE
"No compiler needed" is a lie, on Linux

### ISSUE THREAD

**Issue by mjl** [wbond/oscrypto#53]
(Sorry for the clickbaity title, I couldn't resist)

> No compiler needed, ever. … Just distribute the Python source files, any way you want.

  This is not correct on Linux systems. If you check the docs for `ctypes.util.find_library()`, it says

`On Linux, find_library() tries to run external programs (/sbin/ldconfig, gcc, objdump and ld) to find the library file.`

  Which means, not only does it need a compiler, it needs it on runtime! You cannot use oscrypto on a system **without a full development environment**, which kind of defeats the purpose of a library.

  The only way to make it work on a production system is calling `use_openssl()` to pass hard coded paths early in your app, which also is somewhat of a suboptimal hack.

  I think oscrypto should call find_library() while installing and cache the openssl/libcrypto paths somehow, so that an install from a wheel package will work without further shenanigans?

**Comment by mjl** [comment]
To be more specific, this is a problem mostly under _Alpine Linux_, which only implements a minimal version of `ldconfig` that does not support caching, thus `find_library()` falls back onto the expensive development toolchain gcc/objdump/ld method.

I'm not sure if one is to classify that as upstream bug, or oscrypto bug, but in any case, calling `find_library()` in production code feels wrong, considering the abovementioned details.

**Comment by wbond** [comment]
I mean, technically you don't need a full compiler since you can provide the paths to OpenSSL.

I don't have any interest in trying to do something like cache library paths on install. I think it you are using it in an env that `find_library()` doesn't work, then having the app/library/framework that is using oscrypto can provide a user-facing configuration mechanism that can pass the info down to oscrypto.

This way oscrypto has deterministic installs, and you can handle the env you are running in.

I'm fine with adding a note to the readme about the situation though.

**Comment by mjl** [comment]
Yes, providing the path was my workaround.

For anyone stumbling over the same problem on Alpine, here's what I came up with. Feel free to stuff it in the readme or link to this issue if you deem it useful.

```python
import sys
import wrapt
import oscrypto._ffi

@wrapt.patch_function_wrapper('oscrypto', '_ffi.get_library')
def get_library(wrapped, instance, args, kwargs):  # pylint: disable=unused-argument
    """Patch oscrypto._ffi.get_library(), as ctypes.util.find_library depends on gcc,
    ldconfig, ld and objdump, all of which are not available in a production build.
    Therefore, as a stopgap measure (that probably will live for several years),
    return a static value for some libraries on linux.
    """

    r = wrapped(*args, **kwargs)

    if not r and sys.platform == 'linux':
        #  args = (name, dylib_name, version)
        name = args[0]
        if name == 'crypto':
            return '/usr/lib/libcrypto.so.1.1'
        elif name == 'ssl':
            return '/usr/lib/libssl.so.1.1'

    return r
```

**Comment by wbond** [comment]
There should be a much simpler way to do this:

```python
from oscrypto import use_openssl

use_openssl('/usr/lib/libcrypto.so.1.1', '/usr/lib/libssl.so.1.1')
```

**Comment by mjl** [comment]
Yes, noted; I think I ran into some problems with `use_openssl()`. I can't remember the details, but that's why I came up with that convoluted patch above. I'll try again and comment here if I hit a problem.

**Comment by wbond** [comment]
That would be helpful if you can. I'd like to have an official, simple way to accomplish what you are doing, which is the intent with `use_openssl()`.

**Comment by mjl** [comment]
Okay, I must have misremembered or I just goofed up when I came up with that solution. It works totally fine with just  `use_openssl()`. My bad, sorry!

A note in the docs would be nice though. The problem with the non-functional lookup because of a castrated `ldconfig` happened to me with the `python:3.x-alpine` docker images.

**Comment by wbond** [comment]
I've added a note to the readme in the Dependencies section about the requirement for OpenSSL and how some Linux installs will require manual configuration.
