### ISSUE TITLE
OSError on macOS 12.2 running on arm

### ISSUE THREAD

**Issue by behrtam** [wbond/oscrypto#56]
Setup: macOS 12.1, oscrypto 1.2.1, Python 3.9.5

Not sure where to even start to look for this problem. Running the newest mac version on arm and not Intel. The OSStatus 62385568 did not give me any clues.

```
/Users/xxx/.local/share/virtualenvs/QpmVhfBc/lib/python3.9/site-packages/oscrypto/_mac/asymmetric.py:1027: in rsa_pkcs1v15_encrypt
    key_length = certificate_or_public_key.byte_size
/Users/xxx/.local/share/virtualenvs/QpmVhfBc/lib/python3.9/site-packages/oscrypto/_asymmetric.py:225: in byte_size
    return self.public_key.byte_size
/Users/xxx/.local/share/virtualenvs/QpmVhfBc/lib/python3.9/site-packages/oscrypto/_mac/asymmetric.py:255: in public_key
    handle_sec_error(res)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

error = 62385568, exception_class = <class 'OSError'>
    
>       raise exception_class(output)
E       OSError: OSStatus 62385568

/Users/xxx/.local/share/virtualenvs/QpmVhfBc/lib/python3.9/site-packages/oscrypto/_mac/_security.py:57: OSError
```

**Comment by wbond** [comment]
Do you know what kind of key it was (RSA, DSA, etc) and what size it was?

**Comment by wbond** [comment]
Actually, from the trace, it must have been an RSA key. If you can determine the key size, that would be helpful for improving the error message.

**Comment by behrtam** [comment]
SHA-256 with RSA Encryption ( 1.2.840.113549.1.1.11 ), Key Size=2.048 bits

**Comment by wbond** [comment]
Could you try a 4096 bit key and see if it errors? 2048 is pretty small for 2022. I recently renewed my code signing cert and Sectigo wouldn’t let me use a 2048 bit key. Perhaps Apple decided to error out on shorter keys now?

**Comment by behrtam** [comment]
4096 bits does run into the same error.

We are using `oscrypto` via `pyas2lib.as2` ... will try to find some time to work on a minimal setup to reproduce this.

**Comment by wbond** [comment]
Is the certificate an RSAPSS cert?

**Comment by magicrobotmonkey** [comment]
Appears to fire these messages in console:
<img width="977" alt="image" src="https://user-images.githubusercontent.com/3372975/168621235-72482f37-708b-4639-8f72-036c019d0830.png">

**Comment by magicrobotmonkey** [comment]
Those might be a red herring? But they're also interspersed with these MacOS error issues: 
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/3372975/168624833-64bd3539-cd8f-4782-8f01-0780b88e876e.png">
