### ISSUE TITLE
secp256r1 seed bytes?

### ISSUE THREAD

**Issue by FrankC01** [wbond/oscrypto#70]
Working with a blockchain that stores the 'keystring' in a base64 string when decoded expects 65 bytes where
The first 33 bytes are the public key
The remaining 32 bytes are the private key

So, for a new key generation I know I do:
```python
    from oscrypto import asymmetric
    public, private = asymmetric.generate_pair('ec', curve='secp256r1')
```

My question is how to get the bytes from the respective keys to b64encode to expected keystring?

Conversely, if I load keystring, decode to bytes... how to instantiate the public and private keys to assert test the round trip?

I'm a newbie but have thick skin :)

**Comment by FrankC01** [comment]
Is this still an active project? Looking for answer to above.

Thanks

**Comment by wbond** [comment]
This project is effectively a free-time project for me, which these days is rather few and far between.

The public and private key objects returned have an `.asn1` property which returns an object from asn1crypto. You should be able to effectively do this:

```python3
public.asn1.dump()
private.asn1.dump()
```

**Comment by FrankC01** [comment]
Sleep well my friend, I eventually figured it out.

My apologies for not closing this when I did (sometime around mid-Feb).
